settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: izual # unique identifier
    name: izual
    description: 'izual'
    url: 'https://izual.me' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: 'tisfeng'
    name: 'tisfeng'
    description: 'tisfeng'
    url: 'https://tisfeng.com'
    method: 'GET'
    expectStatus: 200
    linkable: false


  - id: 'ollama'
    name: 'ollama'
    description: 'ollama'
    url: 'https://ollama.izual.me'
    method: 'GET'
    expectStatus: 200
    linkable: false

  - id: 'one-api'
    name: 'one-api'
    description: 'one-api'
    url: 'https://api.izual.me'
    method: 'GET'
    expectStatus: 200
    linkable: true
